<?php
$connection_error = false;

$connection_error_message = "";

//TODO: once data is implemented, change to host info
$con = @mysqli_connect (hostname: "localhost", username: "cs370", password: "group4", database: "csproject" );

If (mysqli_connect_errno() ){

    $connection_error = true;
    $connection_error_message = "Failed to connect to MySQL: "
        .mysqli_connect_error() ;

}


Function output_error ( $title, $error): void {

    Echo "<span style = 'color: red;'>\n" ;
    Echo "<h2> . $title </h2>\n" ;
    Echo "<h4> . $error  </h4>\n" ;
    Echo "</span>";


}

?>



<html>
<head>
    //TODO: change this to report type
    <link rel="stylesheet" href="style.css">
    <title> Assignment Data Report </title>

</head>

<style>
    //Uncomment this once a boostrap program is implemented
    /*
        .pizzaDataTable{ font-family: Consolas; monospace;
            font-size: larger; border-spacing: 0; }
        .pizzaDataHeaderRow td { font-weight: bold; padding-right: 20px; }
        .pizzaDataRow td {border-bottom: 1px solid #888888; padding-left: 10px; }
        .pizzaDataDetailsCell { padding-left: 10px; font-size: medium; }
        .pizzaDataTable tr:nth-child(2n+2) {background-color: #cccccc;}
    */
</style>

<body>
<?php include "navbar.phtml" ?>
//Again, change this to report type
<h1>Assignment Report </h1>

<?php if ($connection_error ) {

    output_error( title: "Database connection failure!", error: $connection_error_message );
}else{

//TODO: once a table is chosen, change this info to the info of the table.
    //for example, add in firstname for student.
    Function output_table_open():void {
        Echo "<table class=’AssignmentDataTable’>\n" ;
        Echo "<tr class = ‘AssignmentDataHeaderRow’>\n" ;
        Echo " <th>CourseID</th>\n" ;
        Echo " <th>Location</th>?\n";
        Echo " <th>MeetTime</th>\n" ;
        Echo " <th>MeetDay</th>?\n";
        Echo " <th>CourseName</th>\n" ;
        Echo " </tr>\n ";

    }

    Function output_table_close(): void{
        Echo "</table>\n" ;
    }

//TODO: change these to be the same as the table above
    Function Output_Course_Row($CourseID, $Location, $MeetTime,
    $MeetDay, $CourseName): void {

        Echo "<tr class = ‘DepartmentDataRow’>\n" ;
        Echo "       <td>" . $CourseID . "</td>\n" ;
        Echo "       <td>" . $Location. " </td>\n";
        Echo "       <td>" . $MeetTime . "</td>\n" ;
        Echo "       <td>" . $MeetDay . " </td>\n";
        Echo "       <td>" . $CourseName . "</td>\n" ;
        Echo "</tr>\n" ;
    }



//TODO: change these to be the 2nd table in the report
    Function Output_Course_Info($courses, $Assignments): void{



        $courses_str = "None" ;
        $professors_str = "None" ;
        If (sizeof( $courses ) > 0){
            $courses_str = implode ( separator: " ", array: $courses ) ;
        }
        If (sizeof($Assignments) > 0 ){
            $professors_str = "AssignmentType - " . "AssignmentDate - " . "DueDate - " . "AssignmentID - "
                . "Grade - " . "CourseID - " . "AssignmentName - ". "</td>\n  </tr>\n  <tr> <td> - ";
            array_pop($Assignments);
            $professors_str = $professors_str . implode ( separator: " - ", array: $Assignments ) ;
        }

        Echo "<tr>\n";
        Echo "   <td colspan= ‘2’ class=’DepartmentDatacell’\n";
        Echo "Department: " . $courses_str . " <br/>\n" ;
        Echo " - " .$professors_str . " - <br/>\n";
        Echo "</td>\n" ;
        Echo "</tr>\n" ;

    }




    //$query -> "command seen below" . " put a space between the start" . " use periods to separate lines ";

    $query = " SELECT * FROM  courses t0 INNER JOIN assignments t1 ON 
     t0.CourseID = t1.CourseID ";
    $result = mysqli_query ( $con, $query );

    If ( ! $result) {
        If (mysqli_errno ($con)) {
            Output_error (title: "Data retrieval failure!", error: mysqli_error($con));

        }else{
            Echo "No data found!";
        }

    } else {
        output_table_open();
        $CourseID = null;
        $courses = array();
        $assignments = array();
        $I = 0;
        While ($row = $result->fetch_array()){
            if( $CourseID != $row [ "CourseID" ]){
                If ($CourseID != null ) {
                    Output_Course_Info($courses, $assignments) ;
                }
                Output_Student_Row ( $row ["CourseID"], $row ["Location"], $row["MeetTime"]
                , $row["MeetDay"], $row ["CourseName"]);


                $courses = array () ;
                $assignments = array() ;

            }
//TODO: change these to match the data being imported. You just need to change the ""
            //unless more is being added.
            If (! in_array($row[ "CourseID" ], $courses )){
                $courses[] = $row ["CourseID"] ;
            }

            If (!in_array ($row ["AssignmentId" ], $assignments )) {
                $assignments[$I] = $row ["AssignmentType"];
                $I++;
                $assignments[$I] = $row ["AssignmentDate"];
                $I++;
                $assignments[$I] = $row ["DueDate"];
                $I++;
                $assignments[$I] = $row ["AssignmentId"];
                $I++;
                $assignments[$I] = $row ["Grade"];
                $I++;
                $assignments[$I] = $row ["CourseID"];
                $I++;
                $assignments[$I] = $row ["AssignmentName"];
                $I++;
            }



            if(sizeof($assignments)>0){
                $assignments[$I] = "</td>\n  </tr>\n  <tr> <td>";
                $I++;

            }

            $CourseID = $row [ "CourseID" ];


        }
        If ($CourseID != null ) {
            Output_Course_Info ($courses, $assignments) ;
        }

        output_table_close() ;
    }

}

?>

</body>
</html>


