<?php
$connection_error = false;

$connection_error_message = "";

//TODO: once data is implemented, change to host info
$con = @mysqli_connect (hostname: "localhost", username: "cs370", password: "group4", database: "csproject" );

If (mysqli_connect_errno() ){

    $connection_error = true;
    $connection_error_message = "Failed to connect to MySQL: "
        .mysqli_connect_error() ;

}


Function output_error ( $title, $error): void {

    Echo "<span style = 'color: red;'>\n" ;
    Echo "<h2> . $title </h2>\n" ;
    Echo "<h4> . $error  </h4>\n" ;
    Echo "</span>";


}

?>



<html>
<head>
    //TODO: change this to report type
    <link rel="stylesheet" href="style.css">
    <title> Student Data Report </title>

</head>

<style>
    //Uncomment this once a boostrap program is implemented
    /*
        .pizzaDataTable{ font-family: Consolas; monospace;
            font-size: larger; border-spacing: 0; }
        .pizzaDataHeaderRow td { font-weight: bold; padding-right: 20px; }
        .pizzaDataRow td {border-bottom: 1px solid #888888; padding-left: 10px; }
        .pizzaDataDetailsCell { padding-left: 10px; font-size: medium; }
        .pizzaDataTable tr:nth-child(2n+2) {background-color: #cccccc;}
    */
</style>

<body>
<?php include "navbar.phtml" ?>
//Again, change this to report type
<h1>Student Report </h1>

<?php if ($connection_error ) {

    output_error( title: "Database connection failure!", error: $connection_error_message );
}else{

//TODO: once a table is chosen, change this info to the info of the table.
    //for example, add in firstname for student.
    Function output_table_open():void {
        Echo "<table class=’StudentDataTable’>\n" ;
        Echo "<tr class = ‘StudentHeaderRow’>\n" ;
        Echo " <th>First name</th>\n" ;
        Echo " <th>Last name</th>\n" ;
        Echo " <th>Email</th>\n" ;
        Echo " <th>Student ID</th>\n" ;
        Echo " <th>Major</th>\n" ;
        Echo " </tr>\n ";

    }

    Function output_table_close(): void{
        Echo "</table>\n" ;
    }

//TODO: change these to be the same as the table above
    Function Output_Student_Row($Fname, $Lname, $Email, $StudentID, $Grade ): void {

        Echo "<tr class = ‘StudentDataRow’>\n" ;
        Echo "       <td>" . $Fname . "</td>\n" ;
        Echo "       <td>" . $Lname . "</td>\n" ;
        Echo "       <td>" . $Email . "</td>\n" ;
        Echo "       <td>" . $StudentID . "</td>\n" ;
        Echo "       <td>" . $Grade . "</td>\n" ;
        Echo "</tr>\n" ;
    }



//TODO: change these to be the 2nd table in the report
    Function Output_Course_Info($Courses, $Students): void{



        $Students_Str = "None" ;
        $Courses_Str = "None" ;
        If (sizeof( $Students ) > 0){
            $Students_Str = implode ( separator: " ", array: $Students ) ;
        }
        If (sizeof($Courses) > 0 ){
            $Courses_Str = "CourseID - "  . "</td>\n  </tr>\n  <tr> <td> - ";
            array_pop($Courses);
            $Courses_Str = $Courses_Str . implode ( separator: " - ", array: $Courses ) ;
        }

        Echo "<tr>\n";
        Echo "   <td colspan= ‘2’ class=’DepartmentDatacell’\n";
        Echo "Department: " . $Students_Str . " <br/>\n" ;
        Echo " - " .$Courses_Str . " - <br/>\n";
        Echo "</td>\n" ;
        Echo "</tr>\n" ;

    }




    //$query -> "command seen below" . " put a space between the start" . " use periods to separate lines ";

    $query = " SELECT * FROM  studentscourselist t0 INNER JOIN students t1 ON 
     t0.StudentID = t1.StudentID ";
    $result = mysqli_query ( $con, $query );

    If ( ! $result) {
        If (mysqli_errno ($con)) {
            Output_error (title: "Data retrieval failure!", error: mysqli_error($con));

        }else{
            Echo "No data found!";
        }

    } else {
        output_table_open();
        $StudentID = null;
        $Courses = array();
        $Students = array();
        $I = 0;
        While ($row = $result->fetch_array()){
            if( $StudentID != $row [ "StudentID" ]){
                If ($StudentID != null ) {
                    Output_Course_Info($Courses, $Students) ;
                }
                Output_Student_Row ( $row ["Fname"], $row ["Lname"],
                    $row ["Email"], $row ["StudentID"], $row ["Major"]);


                $Courses = array () ;
                $Students = array() ;

            }
//TODO: change these to match the data being imported. You just need to change the ""
            //unless more is being added.
            If (! in_array($row[ "StudentID" ], $Students )){
                $Students[] = $row ["StudentID"] ;
            }

            If (!in_array ($row ["CourseID" ], $Courses )) {
                $Courses[$I] = $row ["CourseID"];
                $I++;
            }



            if(sizeof($Courses)>0){
                $Courses[$I] = "</td>\n  </tr>\n  <tr> <td>";
                $I++;

            }

            $StudentID = $row [ "StudentID" ];


        }
        If ($StudentID != null ) {
            Output_Course_Info ($Courses, $Students) ;
        }

        output_table_close() ;
    }

}

?>

</body>
</html>


