<?php
$import_attempted = false;
$import_succeeded = false;
if( $_SERVER[ "REQUEST_METHOD"] = "POST" ){
    $import_attempted = true;

    $con = @mysqli_connect( hostname:"localhost", username:"local_user",
        Password:"pizza", database:"pizza_db");

if( mysqli_connect_errno() ) {
    $import_error_message = "Failed to connect to MySQL: "
    . mysqli_connect_error() ;
}else{

    Try{
        $contents = file_get_contents( $_FILES [ "importFile"] [ "tmp_name"]);
        $lines = explode ( separator: "\n", string: $contents ) ; //$contents missing here

        Foreach ( $lines as $line ){
            $parsed_csv_line = str_getcsv ( $line ) ;
            //TODO: do something with the parsed data
            //for full credit, track how many rows were inserted vs. updated
            //in each entity
        }
        $import_succeeded = true ;

    }
    catch( Error $exception ){
        $import_error_message = $exception->getMessage()
            . "at: " . $exception->getFile()
        . " (line ". $exception->getLine() . ") <br/>" ;
}

}
}
?>


<html>
<head>
    <title>Database Name Import</title>

</head>

<body>

<h1>Student Data Import</h1>



<?php

if($import_attempted ) {
    if($import_succeeded) {?>
        <h1><span style=’color: green;”>Import Succeeded!</span></h1>
    <?php } else {?>
        <h1><span style = “color: red;”> Import Failed!</span></h1>
        <span> style = “color: red;”
        <?php echo $import_error_message ; ?></span>
        <br/><br/>
    <?php }
}

?>




<form method = "post" enctype="multipart/form-data">
    File: <input type = "file" name = "ImportFile"/>
    <br/><br/>
    <input type = "submit" value = "Upload Data"/>

</form>

</body>

<html>
